//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ders()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<int> AkademisyenId { get; set; }
        public Nullable<int> Gun { get; set; }
        public string Saat { get; set; }
        public string ToplamDersSaati { get; set; }
        public Nullable<int> Kredi { get; set; }
        public Nullable<int> VizeOran { get; set; }
        public Nullable<int> FinalOran { get; set; }
    
        public virtual Akademisyen Akademisyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
}
